server:
  port: 9999
  servlet:
    context-path: /
# Socket配置
socket:
  # 监听端口 2323
  port: 2323
  # 线程池 - 保持线程数 20
  pool-keep: 20
  # 线程池 - 核心线程数 10
  pool-core: 10
  # 线程池 - 最大线程数 20
  pool-max: 30
  # 线程队列容量 10
  pool-queue-init: 10

spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.18.1.91:3306/graduation?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: xxxx
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  configuration:
#    map-underscore-to-camel-case: true
#    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath*:mapper/**/*Mapper.xml
#  global-config:
#    # 逻辑删除配置
#    db-config:
#      # 删除前
#      logic-not-delete-value: 1
#      # 删除后
#      logic-delete-value: 0